#!/bin/sh
#SBATCH --partition=long
#SBATCH --job-name=MetaVarAnalysis
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH --share
#SBATCH --mem-per-cpu=15000
#SBATCH --time=100:00:00
#SBATCH --output=x.%j.out
#SBATCH --error=x.%j.err
#SBATCH --mail-type=FAIL

/data/scratch/bdesilva/software/parallel-20160922/src/parallel --link -k python run_genome.py -v {1} -p pair_file.txt -g {2} -o output_new_data ::: /data/scratch/rkumar/work/METAG-PROJ/JG-BIG/GATK-MULTISNP/*/*.vcf ::: /data/scratch/rkumar/work/BRODY/Project2/1/comb_genomes2/*.gff
